name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11 for backend tests
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run backend tests
      run: mvn test
      working-directory: ./back

    - name: Set up Node.js for frontend tests
      uses: actions/setup-node@v2
      with:
        node-version: '18.13'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./front

    - name: Run frontend tests
      run: ng test --watch=false --browsers=ChromeHeadless
      working-directory: ./front
