name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  frontend-build-test:
  
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13'
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./front
        
      - name: Build frontend
        run: ng build 
        working-directory: ./front
        
      - name: Run frontend tests
        run: ng test --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: ./front

      - name: Archive frontend coverage report
        uses: actions/upload-artifact@v2
        with:
          name: frontend-coverage
          path: ./front/coverage/bobapp/lcov.info

  backend-build-test:
  
    name: Backend Build and Test
    runs-on: ubuntu-latest
    needs: frontend-build-test
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Build backend
        run: mvn package
        working-directory: ./back
        
      - name: Run backend tests
        run: mvn test
        working-directory: ./back

      - name: Archive backend target directory
        uses: actions/upload-artifact@v2
        with:
          name: backend-target
          path: ./back/target/classes

      - name: Archive backend test results
        uses: actions/upload-artifact@v2
        with:
          name: backend-test-results
          path: ./back/target/site/jacoco/jacoco.xml

  sonarcloud-analysis:
  
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [frontend-build-test, backend-build-test]
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Download frontend coverage report
        uses: actions/download-artifact@v2
        with:
          name: frontend-coverage
          path: ./front/coverage/bobapp
  
      - name: Download backend target directory
        uses: actions/download-artifact@v2
        with:
          name: backend-target
          path: back/target/classes
      
      - name: Download backend test results
        uses: actions/download-artifact@v2
        with:
          name: backend-test-results
          path: back/target/site/jacoco

  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build-push:
    name: Docker Image Build and Push
    runs-on: ubuntu-latest
    needs: sonarcloud-analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker image (Front-End)
        uses: docker/build-push-action@v2
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: cecigiu2b/bobapp:front-latest
      - name: Build and push Docker image (Back-End)
        uses: docker/build-push-action@v2
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: cecigiu2b/bobapp:back-latest

