name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./front

      - name: Run tests and reports
        run: npm test -- --coverage
        working-directory: ./front

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and analyze (Back-End)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify
          mvn sonar:sonar \
            -Dsonar.projectKey=joff_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-back \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=cecilia-giusti \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./back

      - name: Cache SonarCloud packages (Back-End)
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sonar-cache-

      - name: Cache Maven packages (Back-End)
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build and analyze (Front-End)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify
          mvn sonar:sonar \
            -Dsonar.projectKey=joff_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-front \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=cecilia-giusti \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./front

      - name: Cache SonarCloud packages (Front-End)
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-sonar-cache-

      - name: Cache Node modules (Front-End)
        uses: actions/cache@v2
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-

      - name: Cache Maven packages (Front-End)
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

